### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cye18** [zhaoolee/WordPressXMLRPCTools#11]
这是一个非常好的工具，感谢作者。

我想把它用到自己的项目上，但这个repo本身没有License。请问能否用于个人用途？应该遵循什么license？

谢谢。

**Comment by zhaoolee** [comment]
可以用于个人用途，同Linux一样，license 为 GPL
Chengwei Ye ***@***.***> 于2022年6月20日周一 05:31写道：
