### ISSUE TITLE
怎么修改地址是文章id而不是文件名呢

### ISSUE THREAD

**Issue by cyole** [zhaoolee/WordPressXMLRPCTools#2]
自动创建的文章链接怎么改成id形式呢  类似/p/74

**Comment by zhaoolee** [comment]
这个脚本不支持id形式, 选用文件英文命名的原因是, url自带文件名, 有利于SEO


李宇杰 ***@***.***> 于2021年4月23日周五 下午5:46写道：

**Comment by zhaoolee** [comment]
不支持

李宇杰 ***@***.***> 于2021年4月23日周五 17:46写道：
